#!/bin/bash
path="/usr/share/hydriam/"
echo "Starting Hydriam..."
echo "Path: $path"
echo "Dev: $1"
echo "----------------------"

if [ $1 == "--dev" ]; then
    nw-sdk $path --enable-transparent-visuals --disable-gpu
else
    nw $path --enable-transparent-visuals --disable-gpu
fi
